DROP TABLE APP.COMPANY;
CREATE TABLE APP.COMPANY (
	companyName VARCHAR(50) NOT NULL,
	companyAddress VARCHAR(150) NOT NULL,
	companyCity VARCHAR(50) NOT NULL,
	gstNumber VARCHAR(20),
	PRIMARY KEY(gstNumber),
	createdAt TIME DEFAULT CURRENT_TIME,
	updatedAt TIME DEFAULT CURRENT_TIME
);
INSERT INTO APP.COMPANY VALUES('Ankit', 'Rajkot', 'Gujarat', 'nthikevojaa', DEFAULT, default);

DROP TABLE APP.CUSTOMER;
CREATE TABLE APP.CUSTOMER (
    customerId INT PRIMARY KEY, 
    name VARCHAR(30) NOT NULL,
    gstNumber VARCHAR(20) NOT NULL UNIQUE,
    address VARCHAR(50) NOT NULL,
    city VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    phone VARCHAR(10) NOT NULL UNIQUE,
    pincode VARCHAR(10) NOT NULL,
    password VARCHAR(30) NOT NULL,
    lastLogin TIME,
    createdAt TIME DEFAULT CURRENT_TIME,
    updatedAt TIME DEFAULT CURRENT_TIME
);
INSERT into APP.CUSTOMER VALUES(103, 'Ankit', '6465vsdvs', 'aiugviwse64rg6e846hgeher', 'Rajkot', 'skduvs', 'iugvwuie', 'viy65we', 'sudvsskuv', CURRENT_TIME, CURRENT_TIME, CURRENT_TIME);

DROP TABLE APP.EMPLOYEE;
CREATE TABLE APP.EMPLOYEE (
	employeeId INT PRIMARY KEY,
	userName VARCHAR(30) NOT NULL UNIQUE,
	password varchar(30)NOT NULL,
	lastLogin TIME,
	createdAt TIME DEFAULT CURRENT_TIME,
	updatedAt TIME DEFAULT CURRENT_TIME 
);
INSERT INTO APP.EMPLOYEE VALUES(104, 'SDKV', 'DIUGVI', CURRENT_TIME, CURRENT_TIME, CURRENT_TIME);

--DROP TABLE APP.GSTTYPE;
--CREATE TABLE APP.GSTTYPE (
--    gstTypeId INT PRIMARY KEY,
--	type varchar(20) NOT NULL
--);
--INSERT INTO APP.GSTTYPE VALUES(1, 'TYPE1');
--INSERT INTO APP.GSTTYPE VALUES(2, 'TYPE2');

DROP TABLE APP.INVOICE;
CREATE TABLE APP.INVOICE (
    invoiceId INT primary key,
    invoiceDate Date NOT NULL,
    orderId INT NOT NULL UNIQUE,
    gstType VARCHAR(20) CONSTRAINT gstType_ck CHECK (gstType IN ('INTER STATE', 'SAME STATE')),
    gstAmount FLOAT DEFAULT 0.0,
    totalInvoiceAmount FLOAT DEFAULT 0,
    status VARCHAR(10) CONSTRAINT statusInvoice_ck CHECK (status IN ('PAID', 'UNPAID')), 
    createdAt TIME DEFAULT CURRENT_TIME,
    updatedAt TIME DEFAULT CURRENT_TIME,
    FOREIGN KEY (orderId) REFERENCES APP.ORDERDETAILS(orderId)
--    FOREIGN KEY (gstTypeId) REFERENCES APP.GSTTYPE(gstTypeId),
--    FOREIGN KEY (customerId) REFERENCES APP.CUSTOMER(customerId)
);
INSERT INTO APP.INVOICE VALUES(101, CURRENT_DATE, 55555, 'INTER STATE', 1052.16, 649464.65, 'UNPAID', DEFAULT, DEFAULT);
INSERT INTO APP.INVOICE VALUES(102, CURRENT_DATE, 55556, 'INTER STATE', 1052.16, 649464.65, 'UNPAID', DEFAULT, DEFAULT);
INSERT INTO APP.INVOICE VALUES(103, CURRENT_DATE, 55557, 'INTER STATE', 1052.16, 649464.65, 'UNPAID', DEFAULT, DEFAULT);


DROP TABLE APP.ORDERDETAILS;
CREATE TABLE APP.ORDERDETAILS (
    orderId INT,
    orderDate DATE DEFAULT CURRENT_DATE NOT NULL,
    customerId INT NOT NULL,
    employeeId INT NOT NULL,
    totalOrderValue DOUBLE NOT NULL, 
    shippingCost DOUBLE NOT NULL, 
    shippingCompany VARCHAR(20) NOT NULL,
    status VARCHAR(10) CONSTRAINT status_ck CHECK (status IN ('PENDING', 'APPROVED','COMPLETED','EXPIRED')),
    createdAt TIME DEFAULT CURRENT_TIME,
    updatedAt TIME DEFAULT CURRENT_TIME,   
    PRIMARY KEY(orderId),
    FOREIGN KEY (customerId) REFERENCES APP.CUSTOMER(customerId),
    FOREIGN KEY (employeeId) REFERENCES APP.EMPLOYEE(employeeId)
);
INSERT INTO APP.ORDERDETAILS VALUES(55555, DEFAULT, 103, 104, 1321.56, 50.01, 'EKART', 'PENDING', default, default);
INSERT INTO APP.ORDERDETAILS VALUES(55556, DEFAULT, 103, 104, 1321.56, 50.01, 'EKART', 'PENDING', default, default);
INSERT INTO APP.ORDERDETAILS VALUES(55557, DEFAULT, 103, 104, 1321.56, 50.01, 'EKART', 'PENDING', default, default);


-- Single order can have multiple products
DROP TABLE APP.ORDERPRODUCTS;
CREATE TABLE APP.ORDERPRODUCTS (
    orderId int,
    productId int,  
    primary key (orderId, productId)
);

--DROP TABLE APP.ORDERSTATUS;
--CREATE TABLE APP.ORDERSTATUS (
--        orderStatusId INT PRIMARY KEY,
--        status VARCHAR(20) NOT NULL
--);

DROP TABLE APP.PRODUCT;
CREATE TABLE APP.PRODUCT (
    productId int,
   	productName varchar(20) NOT NULL,
    productPrice float NOT NULL,
  	productCategory VARCHAR(10) CONSTRAINT productCategory_ck CHECK (productCategory IN ('LEVEL 1', 'LEVEL 2','LEVEL 3')),
 	companyId VARCHAR(20) NOT NULL,
    createdAt TIME DEFAULT CURRENT_TIME,
    updatedAt TIME DEFAULT CURRENT_TIME,
    PRIMARY KEY(productId),
    FOREIGN KEY (companyId) REFERENCES APP.COMPANY(gstNumber)
);
INSERT INTO APP.PRODUCT VALUES(1, 'P1', 5564.54, 'LEVEL 1', 'nthikevojaa', DEFAULT, DEFAULT);
INSERT INTO APP.PRODUCT VALUES(2, 'P1', 5564.54, 'LEVEL 2', 'nthikevojaa', DEFAULT, DEFAULT);
INSERT INTO APP.PRODUCT VALUES(3, 'P1', 5564.54, 'LEVEL 3', 'nthikevojaa', DEFAULT, DEFAULT);


DROP TABLE APP.PRODUCTCATEGORY;
CREATE TABLE APP.PRODUCTCATEGORY (
	categoryId int, 
    categoryName varchar(20),
    primary key (categoryId)
);

DROP TABLE APP.SHIPPINGCOMPANY;
CREATE TABLE APP.SHIPPINGCOMPANY (
    companyId int,
    companyName varchar(20),  
    primary key (companyId)
);